// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVkLck6S9r1JkEWUn4aS01qa3xPbvoiY4',
    appId: '1:287436551886:web:80e7a07449e7263a5e029f',
    messagingSenderId: '287436551886',
    projectId: 'newsapp-373a3',
    authDomain: 'newsapp-373a3.firebaseapp.com',
    storageBucket: 'newsapp-373a3.appspot.com',
    measurementId: 'G-0JN9MPJEZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOnPEIwr5OlgeqJ6VhK2JwsbQ4RUW_XMk',
    appId: '1:287436551886:android:adab2547fba1a16b5e029f',
    messagingSenderId: '287436551886',
    projectId: 'newsapp-373a3',
    storageBucket: 'newsapp-373a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRn3S1ZoQ_TgQPf5vmSBOsDiat2zwhRM',
    appId: '1:287436551886:ios:613712ff873785655e029f',
    messagingSenderId: '287436551886',
    projectId: 'newsapp-373a3',
    storageBucket: 'newsapp-373a3.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwRn3S1ZoQ_TgQPf5vmSBOsDiat2zwhRM',
    appId: '1:287436551886:ios:a46badd3096cf23d5e029f',
    messagingSenderId: '287436551886',
    projectId: 'newsapp-373a3',
    storageBucket: 'newsapp-373a3.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
